POST http://localhost:3000/diaryposts
content-type: application/json

{
    "username": "kalle",
    "postName": "Status idag",
    "text": "Hej hej idag är en sådär dag"
}

###

get http://localhost:3000/diaryposts

###

POST http://localhost:3000/users
content-type: application/json

{
    "username": "kalle"
}

###